spring:
  data:
    redis:
      database: 3
      host: localhost
      port: 16379
      password: 123456

      lettuce:
        pool:
          enabled: true
      jedis:
        pool:
          enabled: false

      shard:
        size: 600000