server:
  port: 7200

spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.function.FunctionConfiguration

  cloud:
    stream:
      bindings:
        kinesisEvent-in-0:
          destination: dev_kinesis_event
          group: kinesis-event-group
          content-type: text/json
      kinesis:
        binder:
          checkpoint:
            table: dev_kinesis_meta_data_store
          locks:
            table: dev_kinesis_lock_registry
          auto-create-stream: true
          auto-add-shards: false
    function:
      definition: kinesisEvent;
