spring:
  profiles:
    active: local
  application:
    name: api
    description: "api"

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /monitor
      path-mapping:
        health: healthcheck
  health:
    binders:
      enabled: false

springdoc:
  use-fqn: true
  api-docs:
    enabled: false
    path: /swagger-ui/api-docs
  swagger-ui:
    enabled: false
    path: /index.html

server:
  servlet:
    context-path: /api
